server:
  port: 0
spring:
  application:
    name: config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    config:
      server:
        git:
          uri: file:///C://Users/dell/Documents/Git/shorturl-backend-config
          search-paths: config-dev-sjc/spring-cloud-nosql
          default-label: master
