server:
  port: 0
spring:
  application:
    name: config
  cloud:
    consul:
      host: 47.102.118.113
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
    config:
      server:
        git:
          uri: https://github.com/SE-summerHomework-team-shorturl/shorturl-backend-config
          username: JerryCrab
          password: bayun3383youzi
          default-label: master
          search-paths: config-test-sjc/spring-cloud-nosql
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
