server:
  port: 8001

spring:
  application:
    name: redirect-service # 应用名称

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
    instance:
      instance-id: redirect-service   # 在eureka中显示对应的服务名字
      prefer-ip-address: true     #在eureka中下边的访问路径可以显示IP地址 #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
