server:
  port: 8080

spring:
  application:
    name: security-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
