server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      server:
        git:
          uri: file:///C://Users/dell/Documents/Git/shorturl-backend-config
          search-paths: config-dev-sjc
          default-label: master
