security:
  oauth2:
    client:
      client-id: client
      client-secret: client-secret
    authorization:
      check-token-access: http://localhost:8081/oauth/check_token
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: false
    fetch-registry: false
