version: "3.8"
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  redis-noeviction:
    build: ./redis-noeviction
    volumes:
      - redis-noeviction-data:/data
    ports:
      - 6379:6379
  redis-cache:
    build: ./redis-cache
    volumes:
      - redis-cache-data:/data
    ports:
      - 6380:6379
  consul:
    image: consul:latest
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
    depends_on:
      - consul
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  config:
    build: ./short-url-config
    depends_on:
      - consul
  gateway:
    build: ./short-url-gateway
    ports:
      - 8080:8080
    depends_on:
      - consul
      - config
  redirect:
    build: ./short-url-redirect
    depends_on:
      - consul
      - config
      - mongo
      - redis-cache
  auth:
    build: ./short-url-auth
    depends_on:
      - consul
      - config
      - mongo
  user:
    build: ./short-url-user
    depends_on:
      - consul
      - config
      - redis-noeviction
      - mongo
  shortener:
    build: ./short-url-shortener
    depends_on:
      - consul
      - config
      - auth
      - gateway
  manager:
    build: ./short-url-manager
    depends_on:
      - consul
      - config
      - auth
      - gateway
volumes:
  mongo-data:
  redis-noeviction-data:
  redis-cache-data:
